### PR TITLE
Add ethereum transaction v2 fee properties for wallet connect

### PR DESCRIPTION
**Pull request by ant013**
ref #3871

### CODE REVIEW

**Review by mNizhurin — APPROVED** [review]

**Review by ealymbaev — APPROVED** [review]

**Comment by Tomcherry117687** [comment]
merged-approved

**Comment by Tomcherry117687** [comment]
merged

**Comment by Tomcherry117687** [comment]
merged-unstoppablewallet-iOS

**Comment by Tomcherry117687** [comment]
merged unstoppablewallet-into-version-0.24

**Comment by Tomcherry117687** [comment]
merged-unstoppablewallet-iOS-into-version-0.24

**Pull request merged**
